baseURL = "eoghanriley.dev"
defaultContentLanguage = "en"
languageCode = "en-us"

title = "eoghanriley.dev"

theme = "gokarna"

# Automatically generate robots.txt
enableRobotsTXT = true

[menu]
  [[menu.main]]
    identifier = "home"
    url = ""
    name = "Home"
    weight = 1
  
  [[menu.main]]
    #unique identifier for a menu item
    identifier = "posts"
    url = "/posts/"

    # You can add extra information before the name (HTML format is supported), such as icons
    pre = ""

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Posts"

    # Weights are used to determine the ordering
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
  
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    url = "https://github.com/eoghanriley"
    weight = 5

    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"

[params]
  description = "The portfolio and blog for Eoghan Riley."

  accentColor = "#000000"

  metaKeywords = ["blog", "portfolio", "Eoghan Riley"]

  showPostsOnHomePage = "popular"

  socialIcons = [
    { name = "github", url = "https://www.github.com/eoghanriley" },
    { name = "twitter", url = "https://twitter.com/Seniorquesopan1" },
    { name = "linkedin", url = "https://www.linkedin.com/in/eoghan-riley-ba1529245/" }
  ]

pygmentsStyle = "dracula"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 5
    ordered = false